services:
  - type: web
    name: gdg-utcn-event-planner
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_PATH
        value: /opt/render/project/src/server/data/database.sqlite
      - key: ADMIN_CODE
        value: GDGoCEIMAITARI
